nfl_data_pipeline:
  outputs:
    dev:
      type: duckdb
      path: /Users/dougstrouth/Documents/Code/datasets/sports/NFL/nfl.duckdb
      threads: 2

    prod:
      type: duckdb
      path: /Users/dougstrouth/Documents/Code/datasets/sports/NFL/nfl.duckdb
      threads: 4

  target: dev
