WITH team_aussportsbetting_info AS (
    SELECT
        a.Date,
        a.Home_Team AS home_team_name,
        th.team_id AS home_team_id,
        a.Away_Team AS away_team_name,
        ta.team_id AS away_team_id,
        a.Home_Score,
        a.Away_Score,
        a.Overtime,
        a.Playoff_Game,
        a.Neutral_Venue,
        a.Home_Odds_Open,
        a.Home_Odds_Min,
        a.Home_Odds_Max,
        a.Home_Odds_Close,
        a.Away_Odds_Open,
        a.Away_Odds_Min,
        a.Away_Odds_Max,
        a.Away_Odds_Close,
        a.Home_Line_Open,
        a.Home_Line_Min,
        a.Home_Line_Max,
        a.Home_Line_Close,
        a.Away_Line_Open,
        a.Away_Line_Min,
        a.Away_Line_Max,
        a.Away_Line_Close,
        a.Home_Line_Odds_Open,
        a.Home_Line_Odds_Min,
        a.Home_Line_Odds_Max,
        a.Home_Line_Odds_Close,
        a.Away_Line_Odds_Open,
        a.Away_Line_Odds_Min,
        a.Away_Line_Odds_Max,
        a.Away_Line_Odds_Close,
        a.Total_Score_Open,
        a.Total_Score_Min,
        a.Total_Score_Max,
        a.Total_Score_Close,
        a.Total_Score_Over_Open,
        a.Total_Score_Over_Min,
        a.Total_Score_Over_Max,
        a.Total_Score_Over_Close,
        a.Total_Score_Under_Open,
        a.Total_Score_Under_Min,
        a.Total_Score_Under_Max,
        a.Total_Score_Under_Close,
        a.Notes
    FROM
        {{ref('check_csv_nfl_asb')}} a
    LEFT JOIN
        {{ ref('check_csv_nfl_teams') }} th ON a.Home_Team = th.team_name
    LEFT JOIN
        {{ ref('check_csv_nfl_teams') }} ta ON a.Away_Team = ta.team_name
)

SELECT
    Date,
    home_team_name,
    home_team_id,
    away_team_name,
    away_team_id,
    Home_Score,
    Away_Score,
    Overtime,
    Playoff_Game,
    Neutral_Venue,
    Home_Odds_Open,
    Home_Odds_Min,
    Home_Odds_Max,
    Home_Odds_Close,
    Away_Odds_Open,
    Away_Odds_Min,
    Away_Odds_Max,
    Away_Odds_Close,
    Home_Line_Open,
    Home_Line_Min,
    Home_Line_Max,
    Home_Line_Close,
    Away_Line_Open,
    Away_Line_Min,
    Away_Line_Max,
    Away_Line_Close,
    Home_Line_Odds_Open,
    Home_Line_Odds_Min,
    Home_Line_Odds_Max,
    Home_Line_Odds_Close,
    Away_Line_Odds_Open,
    Away_Line_Odds_Min,
    Away_Line_Odds_Max,
    Away_Line_Odds_Close,
    Total_Score_Open,
    Total_Score_Min,
    Total_Score_Max,
    Total_Score_Close,
    Total_Score_Over_Open,
    Total_Score_Over_Min,
    Total_Score_Over_Max,
    Total_Score_Over_Close,
    Total_Score_Under_Open,
    Total_Score_Under_Min,
    Total_Score_Under_Max,
    Total_Score_Under_Close,
    Notes
FROM
    team_aussportsbetting_info