version: 2

sources:
  - name: play_by_play
    description: ""
    database: nfl
    schema: play_by_play
    tables:
      - name: depth_charts
        description: ""
      - name: ftn_data
        description: ""
      - name: injuries
        description: ""
      - name: play_by_play
        description: ""
      - name: qbr
        description: ""
      - name: seasonal_pfr
        description: ""
      - name: weekly_pfr
        description: ""
      - name: weekly_rosters
        description: ""

  - name: aus_betting
    description: ""
    database: nfl
    schema: aus_betting
    tables:
      - name: nfl_stadiums
        description: ""
      - name: nfl_teams
        description: ""
      - name: spreadspoke_scores
        description: ""
